# AUDIORECORD:

AUDIORECORD:
  samplerate: 16000  # 采样率
  channels: 1  # 声道数量
  dtype: 'int16' # 音频存储精度
  sampwidth: 2 # 每个样本的字节数，通常为1（8位）或2（16位） 
  audioBufferLenth: 5 # audioBuffer的长度（s） 
  stepLenth: 0.5 # 记录的步长，最小计时为0.5s，即每0.5秒返回一次音频流数据



